#define HELP_LIB_NAME_LENGTH                  20
#define MAX_MSG_LENGTH                        50

#define ID_MAINMENU                            1

#define IDD_MSGBOX                            10

#define IDMSG_CANNOTLOADSTRING               101
#define IDMSG_HELPLOADERROR                  102
#define IDMSG_HELPDISPLAYERROR               103

#define IDM_SETUP                             11

#define IDD_PRINTSETUP                       111

#define IDD_PSTEXT                          1111
#define IDD_PSLISTBOX                       1112
#define IDD_PSJOBPROP                       1113

#define IDM_PRINT                             12
#define IDM_CANCEL                            13

#define LPTHEX_HELP_TABLE                     2

#define IDS_HELPLIBRARYNAME                  201
#define IDS_HELPWINDOWTITLE                  202

#define SUBTABLE_MAIN                         21

#define IDM_HELPINDEX                        211
#define IDM_GENERALHELP                      212
#define IDM_TUTORIAL                         213
#define IDM_USINGHELP                        214
#define IDM_HELPPRODUCTINFO                  215

#define IDD_PRODUCTINFO                       25


/* Help Panels */

/* General Help */
#define HELP_MAIN                           2111

/* Help on Menus */
#define HELP_FILE                           2112
#define HELP_HELP                           2113

/* Help on File Menu */
#define HELP_FILECANCEL                    21121
#define HELP_FILEEXIT                      21122
#define HELP_FILEPRINT                     21123
#define HELP_FILESETUP                     21124

/* Help on Help Menu */
#define HELP_GENERALHELP                   21131
#define HELP_HELPINDEX                     21132
#define HELP_TUTORIAL                      21133
#define HELP_HELPPRODUCTINFO               21134
#define HELP_USINGHELP                     21135

/* Help on Keys */
#define HELP_KEYSHELP                       2131
